AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda function to list VPCs and Subnets and save to DynamoDB

Resources:
  VpcListerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          DYNAMO_TABLE: NetworkResources
      Policies:
        - AmazonEC2ReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)  # Adjust frequency as needed

  NetworkResourcesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: NetworkResources
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ResourceId
          AttributeType: S
      KeySchema:
        - AttributeName: ResourceId
          KeyType: HASH